export enum Mbti {
  INTP = 'INTP',
  INTJ = 'INTJ',
  INFP = 'INFP',
  INFJ = 'INFJ',
  ISTP = 'ISTP',
  ISTJ = 'ISTJ',
  ISFP = 'ISFP',
  ISFJ = 'ISFJ',
  ENTP = 'ENTP',
  ENTJ = 'ENTJ',
  ENFP = 'ENFP',
  ENFJ = 'ENFJ',
  ESTP = 'ESTP',
  ESTJ = 'ESTJ',
  ESFP = 'ESFP',
  ESFJ = 'ESFJ',
}
